# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty
script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without documentation"
before_install:
  - script/update_rubygems_and_install_bundler
  - gem --version
matrix:
  include:
    # Rails dev / 6 builds >= 2.4.10
    - rvm: 2.6.6
      env: RAILS_VERSION='~> 6.0.0'
    - rvm: truffleruby-head
      env: RAILS_VERSION='~> 6.0.0'
    - rvm: truffleruby
      env: RAILS_VERSION='~> 6.0.0'

branches:
  only:
    - truffleruby-ci
